# Generated by Django 3.0.14 on 2023-11-08 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 8, 23, 52, 15, 835683)),
        ),
    ]
